package com.P3LJ2.P3L_J_2.model;
import org.springframework.scheduling.support.SimpleTriggerContext;

import javax.persistence.*;
import java.util.LinkedList;
import java.util.List;

@Access(value= AccessType.FIELD)
public class User{

    private int Id;
    private List<String> argument = new LinkedList<>();

    protected User() {}

//    User constructor
    public User(int Id, String ... args)
    {
        for(String arg : args)
            this.argument.add(arg);
        this.Id = Id;
    }

    //User constructor
    //Id Auto-generated by Hibernate
    public User(String ... args)
    {
        for(String arg : args)
            this.argument.add(arg);
    }

    //return Id
    public int getId() {
        return Id;
    }

    //return any String arguments
    public static void printList(List<String> argument)
    {
        for(String list : argument)
            System.out.printf("%s", list);
        System.out.println();
    }

    public void setId(int id) {
        Id = id;
    }

    public List<String> getArgument() {
        return argument;
    }

    public void setArgument(List<String> argument) {
        this.argument = argument;
    }

    @Override
    public String toString() {
        return "User{" +
                "Id=" + Id +
                ", argument=" + argument +
                '}';
    }

}
